# Generated by Django 5.2.16 on 2026-07-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='senha',
            field=models.CharField(default='123456', max_length=128, verbose_name='Senha'),
        ),
    ]
